services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile # Adjust the path to the Dockerfile
    container_name: fastapi-dev
    ports:
      - "8000:8000" # Expose the app on localhost:8000
    volumes:
      - .:/app # Mount the current directory to the container for live updates
      - /app/__pycache__ # Prevent caching issues
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1