version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_environment
    volumes:
      - ${PROJECT_PATH}:/code-repair-with-llms  # Sync local files with the container
    working_dir: /code-repair-with-llms
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000" # Example for exposing ports
